'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ExternalLink, FileText, Download } from 'lucide-react';

// Paper data
const paperData = {
  arxiv_id: 'test-paper',
  title: 'Test Paper with Folder-Based Routing',
  authors: 'John Doe, Jane Smith',
  abstract: 'This is a test paper to demonstrate folder-based routing in Next.js. The paper includes static data generated by the backend.',
};

export default function PaperPage() {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState('text');
  
  // Test extracted text
  const extractedText = "This is sample extracted text for a test paper. In a real paper, this would be populated with the actual text extracted from the PDF file.";

  return (
    <div className="pb-12">
      {/* Paper Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 mb-8 py-6">
        <div className="max-w-4xl mx-auto px-4">
          <div className="mb-6">
            <Link 
              href="/" 
              className="inline-flex items-center text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 mb-4"
            >
              <ArrowLeft className="w-4 h-4 mr-1" />
              <span>Back to home</span>
            </Link>
            <h1 className="text-2xl sm:text-3xl font-bold leading-tight mb-4">{paperData.title}</h1>
            
            <div className="flex flex-wrap items-center gap-2 text-sm text-gray-500 dark:text-gray-400 mb-4">
              <span className="inline-flex items-center bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-300 px-2.5 py-0.5 rounded-full">
                arXiv ID: {paperData.arxiv_id}
              </span>
              
              <a 
                href={`https://arxiv.org/abs/${paperData.arxiv_id}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400"
              >
                <ExternalLink className="w-3.5 h-3.5 mr-1" />
                <span>View on arXiv</span>
              </a>
              
              <a 
                href={`https://arxiv.org/pdf/${paperData.arxiv_id}.pdf`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400"
              >
                <Download className="w-3.5 h-3.5 mr-1" />
                <span>Download PDF</span>
              </a>
            </div>
          </div>
          
          {paperData.authors && (
            <div className="mb-4">
              <h2 className="text-sm uppercase tracking-wider text-gray-500 dark:text-gray-400 font-medium mb-1">Authors</h2>
              <p className="text-gray-800 dark:text-gray-200">{paperData.authors}</p>
            </div>
          )}
          
          {paperData.abstract && (
            <div className="mb-6">
              <h2 className="text-sm uppercase tracking-wider text-gray-500 dark:text-gray-400 font-medium mb-1">Abstract</h2>
              <div className="bg-gray-50 dark:bg-gray-900/50 rounded-lg p-4 text-gray-800 dark:text-gray-200 text-sm leading-relaxed">
                {paperData.abstract}
              </div>
            </div>
          )}
          
          {/* Tab Navigation */}
          <div className="border-b border-gray-200 dark:border-gray-700">
            <nav className="flex -mb-px space-x-8">
              <button
                onClick={() => setActiveTab('text')}
                className={`py-2 flex items-center border-b-2 font-medium text-sm ${
                  activeTab === 'text' 
                    ? 'border-blue-500 text-blue-600 dark:text-blue-400' 
                    : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                }`}
              >
                <FileText className="w-4 h-4 mr-2" />
                <span>Paper Text</span>
              </button>
              
              <button
                onClick={() => setActiveTab('images')}
                className={`py-2 flex items-center border-b-2 font-medium text-sm ${
                  activeTab === 'images' 
                    ? 'border-blue-500 text-blue-600 dark:text-blue-400' 
                    : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                }`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <span>Figures & Images</span>
              </button>
            </nav>
          </div>
        </div>
      </div>
      
      <div className="max-w-4xl mx-auto px-4">
        {/* Extracted Text */}
        {activeTab === 'text' && (
          <div className="mb-8">
            <h2 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-4">Extracted Text</h2>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg border border-gray-200 dark:border-gray-700 shadow-sm">
              <pre className="whitespace-pre-wrap text-sm text-gray-800 dark:text-gray-200 font-mono leading-relaxed max-h-[800px] overflow-y-auto">
                {extractedText}
              </pre>
            </div>
          </div>
        )}
        
        {/* Images */}
        {activeTab === 'images' && (
          <div className="mb-8">
            <h2 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-4">Figures & Images</h2>
            
            <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6 text-center">
              <p className="text-gray-600 dark:text-gray-400">
                No images available for this paper.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
} 